name: GCP-Foundation
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set Commit Message
        id: commit_message
        run: 'echo "${{ github.event.head.commit.message }}"  > commit_message.txt'

      - name: Check Commit Message
        id: check_commit_message
        run: |
          COMMIT_MESSAGE=$(cat commit_message.txt)

          if echo "$COMMIT_MESSAGE" | grep -oP 'Perform:\s*\K[^ ]*'; then
            echo "Perform task found in commit message"
            PERFORM_NAME=$(echo "$COMMIT_MESSAGE" | grep -oP 'Perform:\s*\K[^ ]*')
            echo "perform_name = $PERFORM_NAME" >> $GITHUB_ENV
          else
            echo "Perform not found in commit message"
          fi

          if echo "$COMMIT_MESSAGE" | grep -oP 'Path:\s*\K[^ ]*'; then
            echo "Path task found in commit message"
            PATH=$(echo "$COMMIT_MESSAGE" | grep -oP 'Path:\s*\K[^ ]*')
            echo "path = $PATH" >> $GITHUB_ENV
          else
            echo "Path not found in commit message"
          fi

      - name: Execute script for plan
        run: |
          chmod +x ./.github/script/execute.sh
          ./.github/script/execute.sh \
            --session-name "${{ github.actor }}" \
            --path_val "${{ env.path_val }}" \
            --help
        shell: bash

      - name: Cleanup Commit Message File
        run: rm commit_message.txt

  terraform-apply:
    if: github.event.pull_request.merged == true && github.ref == 'refs/heads/main'
    name: Test1
    uses: ./.github/workflows/apply.yml
